sitename: "blog.cxbt.kr"
baseURL: "https://blog.cxbt.kr"
languageCode: ko-kr
title: "blog.cxbt.kr ğŸ¦•"
author: cxbt
theme: kaslaanka

enableEmoji: true
hasCJKLanguage: true
pygmentsstyle: "tango"
pygmentscodefences: true

markup:
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2


defaultContentLanguage: ko
languages:
  ko:
    LanguageName: Korean

params:
  baseURL: "https://blog.cxbt.kr"
  sitename: "ğŸ¦•"
  copyrights: CXBT
  brief_about: <center>ë§ˆêµ¬ ì“°ëŠ” ë¸”ë¡œê·¸ â¤ï¸ï¸</center>